export const GET_PERSONALDETAILS = 'ADD_PERSONALDETAILS';
export const PERSONALDETAILS_LOADING = 'PERSONALDETAILS_LOADING';
export const PERSONALDETAILS_FAILED = 'PERSONALDETAILS_FAILED';
export const GET_ACADEMICS = 'ADD_ACADEMICS';
export const ACADEMICS_LOADING = 'ACADEMICS_LOADING';
export const ACADEMICS_FAILED = 'ACADEMICS_FAILED';